[package]
name = "sorting-visualizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
wasm-bindgen = "0.2.89"
wasm-logger = "0.2"
log = "0.4.20"